//users
export const CREATE_USER = 'CREATE_USER';
export const GET_USERS = 'GET_USERS';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_TOKEN = 'GET_USER_BY_TOKEN';
export const GET_USER_CART = 'GET_USER_CART';
export const PUT_ROLE_USER = 'PUT_ROLE_USER';
export const COPY_USER_TO_STORE = 'COPY_USER_TO_STORE';

//products
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';
export const GET_PRODUCT_JOIN_CATEGORY = 'GET_PRODUCT_JOIN_CATEGORY';
export const POST_PRODUCT_JOIN_CATEGORY = 'POST_PRODUCT_JOIN_CATEGORY';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const DELETE_PRODUCT_JOIN_CATEGORY = 'DELETE_PRODUCT_JOIN_CATEGORY';
export const MODIFY_PRODUCT = 'MODIFY_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const POST_PRODUCT_STOCK = "POST_PRODUCT_STOCK";

//categories
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const MODIFY_CATEGORY = 'MODIFY_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

//cart
export const POST_CREATE_CART = 'POST_CREATE_CART';
export const GET_CART_BY_IDUSER = 'GET_CART_BY_IDUSER';
export const POST_PRODUCT_TO_CART = 'POST_PRODUCT_TO_CART';
export const PUT_CHANGE_QUANTITY = 'PUT_CHANGE_QUANTITY';
export const DEL_PRODUCT_TO_CART = 'DEL_PRODUCT_TO_CART';
export const EMPTY_ALL_PRODUCTS_OF_CART = 'EMPTY_ALL_PRODUCTS_OF_CART';
export const COPY_CART_TO_STORE = 'COPY_CART_TO_STORE';

//orders
export const GET_FULL_ORDERS = 'GET_FULL_ORDERS';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ONE_ORDER = "UPDATE_ONE_ORDER";
export const GET_ORDER_WITH_PRODUCTS = "GET_ORDER_WITH_PRODUCTS";
export const GET_ORDER_BY_STATUS = "GET_ORDER_BY_STATUS";


//reviews
export const ADD_REVIEW = 'ADD_REVIEW';
export const GET_REVIEWS = 'GET_REVIEWS';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
//multer
export const GET_IMAGES = 'GET_IMAGES';
export const ADD_IMAGES = 'ADD_IMAGES';
export const DELETE_IMAGES = 'DELETE_IMAGES';

//msj error
export const ERROR_MESSAGE = 'ERROR_MESSAGE';

export const ADD_CATEGORY_PRODUCT = 'ADD_CATEGORY_PRODUCT';
export const REMOVE_CATEGORY_PRODUCT = 'REMOVE_CATEGORY_PRODUCT';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DETAIL_USER = 'DETAIL_USER';
export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const GET_USER_REVIEWS = 'GET_USER_REVIEWS';
export const CREATE_ORDER = 'CREATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const UPDATE_ORDER_TO_CREATE = 'UPDATE_ORDER_TO_CREATE';
export const UPDATE_ORDER_TO_PROCESS = 'UPDATE_ORDER_TO_PROCESS';
export const CHECKOUT_END = 'CHECKOUT_END';
export const UPDATE_ORDER_TO_FULL = 'UPDATE_ORDER_TO_FULL';
export const UPDATE_ORDER_TO_REJECT = 'UPDATE_ORDER_TO_REJECT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_CART = 'DELETE_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_FROM_CART = 'UPDATE_FROM_CART';
export const GET_ORDERS_STATUS = 'GET_ORDERS_STATUS';

export const SHIPPING_ADDRESS = 'SHIPPING_ADDRESS';
